# This is a basic workflow to help you get started with Actions

name: Test output

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runner's shell
      - name: Run a one-line script
        shell: pwsh
        id: generate-number
        run: echo "number=$(echo $RANDOM)" >> "$GITHUB_OUTPUT"
        
      - name: Use Number
        id: use-number
        run: echo "The number is ${{ steps.generate-number.outputs.number }}"

      # Runs a set of commands using the runner's shell
      - name: Run a multi-line script
        run: |
          echo "The name is ${{ steps.generate-name.outputs.outputName }}"
